<?php

namespace Database\Seeders;

use App\Models\Listing;
use Illuminate\Database\Seeder;

class ListingsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $listings = [
            [
                'headline' => 'Profitable Cafe in Downtown',
                'industry' => 'Restaurants & Food',
                'industry_subcategory' => 'Coffee Shops & Cafes',
                'listing_type' => 'Established Business for Sale',
                'location_name' => 'Downtown Cafe',
                'address' => '123 Main St',
                'city' => 'New York',
                'state' => 'NY',
                'zip' => '10001',
                'county' => 'New York',
                'location_confidentiality' => 'Exact Location',
                'email' => 'seller@example.com',
                'phone_number' => '555-0101',
                'asking_price' => 250000,
                'cash_flow' => 85000,
                'gross_revenue' => 350000,
                'ebitda' => '120000',
                'rent' => '3500',
                'year_established' => 2015,
                'seller_financing' => true,
                'business_description' => 'A well-established cafe in the heart of downtown with a loyal customer base and excellent growth potential.',
                'real_estate_type' => 'Leased',
                'building_size' => 1500,
                'lease_expiration' => '2030-12-31',
                'employees' => 5,
                'status' => 'published',
            ],
            [
                'headline' => 'Tech Startup with Recurring Revenue',
                'industry' => 'Online & Technology',
                'industry_subcategory' => 'Software & App Companies',
                'listing_type' => 'Established Business for Sale',
                'location_name' => 'Tech Solutions Inc',
                'address' => '456 Tech Ave',
                'city' => 'San Francisco',
                'state' => 'CA',
                'zip' => '94105',
                'location_confidentiality' => 'City Only',
                'email' => 'seller@example.com',
                'asking_price' => 500000,
                'cash_flow' => 120000,
                'gross_revenue' => 450000,
                'ebitda' => '180000',
                'year_established' => 2018,
                'business_description' => 'SaaS company with 85% recurring revenue and strong growth trajectory.',
                'employees' => 8,
                'status' => 'published',
            ],
            [
                'headline' => 'Beauty Salon with Loyal Clientele',
                'industry' => 'Beauty & Personal Care',
                'industry_subcategory' => 'Hair Salons & Barber Shops',
                'listing_type' => 'Established Business for Sale',
                'location_name' => 'Glamour Salon',
                'address' => '789 Beauty St',
                'city' => 'Miami',
                'state' => 'FL',
                'zip' => '33101',
                'location_confidentiality' => 'Exact Location',
                'email' => 'seller@example.com',
                'phone_number' => '555-0202',
                'asking_price' => 180000,
                'cash_flow' => 75000,
                'gross_revenue' => 220000,
                'ebitda' => '85000',
                'rent' => '2800',
                'year_established' => 2017,
                'business_description' => 'Full-service beauty salon with 5 stations and strong repeat business.',
                'real_estate_type' => 'Leased',
                'building_size' => 2000,
                'employees' => 6,
                'status' => 'published',
            ],
            [
                'headline' => 'Retail Store in Prime Location',
                'industry' => 'Retail',
                'industry_subcategory' => 'Clothing & Accessory Stores',
                'listing_type' => 'Asset Sale',
                'location_name' => 'Urban Fashion',
                'address' => '321 Downtown Plaza',
                'city' => 'Chicago',
                'state' => 'IL',
                'zip' => '60601',
                'location_confidentiality' => 'Exact Location',
                'email' => 'seller@example.com',
                'asking_price' => 150000,
                'cash_flow' => 65000,
                'gross_revenue' => 280000,
                'ebitda' => '75000',
                'rent' => '3200',
                'year_established' => 2016,
                'business_description' => 'Trendy fashion retail store in high foot traffic area.',
                'real_estate_type' => 'Leased',
                'building_size' => 1800,
                'employees' => 4,
                'status' => 'published',
            ],
            [
                'headline' => 'Landscaping Business with Equipment',
                'industry' => 'Service Businesses',
                'industry_subcategory' => 'Landscaping & Yard Services',
                'listing_type' => 'Asset Sale',
                'location_name' => 'Green Thumb Landscaping',
                'address' => '159 Garden Way',
                'city' => 'Austin',
                'state' => 'TX',
                'zip' => '73301',
                'location_confidentiality' => 'City Only',
                'email' => 'seller@example.com',
                'phone_number' => '555-0303',
                'asking_price' => 320000,
                'cash_flow' => 145000,
                'gross_revenue' => 480000,
                'ebitda' => '160000',
                'year_established' => 2014,
                'business_description' => 'Full-service landscaping business with commercial and residential clients.',
                'employees' => 12,
                'status' => 'published',
            ],
            [
                'headline' => 'Restaurant with Full Liquor License',
                'industry' => 'Restaurants & Food',
                'industry_subcategory' => 'Italian Restaurants',
                'listing_type' => 'Established Business for Sale',
                'location_name' => 'Bella Cucina',
                'address' => '654 Italian Way',
                'city' => 'Boston',
                'state' => 'MA',
                'zip' => '02108',
                'location_confidentiality' => 'Exact Location',
                'email' => 'seller@example.com',
                'phone_number' => '555-0404',
                'asking_price' => 420000,
                'cash_flow' => 185000,
                'gross_revenue' => 750000,
                'ebitda' => '210000',
                'rent' => '5800',
                'year_established' => 2013,
                'business_description' => 'Upscale Italian restaurant with full bar and outdoor seating.',
                'real_estate_type' => 'Leased',
                'building_size' => 3500,
                'employees' => 15,
                'status' => 'published',
            ],
            [
                'headline' => 'E-commerce Business - Home Goods',
                'industry' => 'Online & Technology',
                'industry_subcategory' => 'Websites & Ecommerce',
                'listing_type' => 'Established Business for Sale',
                'location_name' => 'HomeStyle Living',
                'address' => 'Online Business',
                'city' => 'Seattle',
                'state' => 'WA',
                'zip' => '98101',
                'location_confidentiality' => 'City Only',
                'email' => 'seller@example.com',
                'asking_price' => 280000,
                'cash_flow' => 95000,
                'gross_revenue' => 320000,
                'ebitda' => '110000',
                'year_established' => 2019,
                'business_description' => 'Profitable e-commerce store specializing in home decor and furnishings.',
                'employees' => 3,
                'status' => 'published',
            ],
            [
                'headline' => 'Car Wash with Real Estate',
                'industry' => 'Automotive & Boat',
                'industry_subcategory' => 'Car Washes',
                'listing_type' => 'Business Real Estate for Sale (No Business Included)',
                'location_name' => 'Sparkle Car Wash',
                'address' => '123 Auto Row',
                'city' => 'Dallas',
                'state' => 'TX',
                'zip' => '75201',
                'location_confidentiality' => 'Exact Location',
                'email' => 'seller@example.com',
                'phone_number' => '555-0505',
                'asking_price' => 850000,
                'cash_flow' => 220000,
                'gross_revenue' => 680000,
                'ebitda' => '250000',
                'year_established' => 2012,
                'business_description' => 'Full-service car wash with 4 self-serve bays and detail center.',
                'real_estate_type' => 'Owned',
                'building_size' => 5000,
                'employees' => 8,
                'status' => 'published',
            ],
            [
                'headline' => 'Dental Practice for Sale',
                'industry' => 'Health Care & Fitness',
                'industry_subcategory' => 'Dental Practices',
                'listing_type' => 'Established Business for Sale',
                'location_name' => 'Smile Dental',
                'address' => '789 Health Ave',
                'city' => 'Denver',
                'state' => 'CO',
                'zip' => '80202',
                'location_confidentiality' => 'Exact Location',
                'email' => 'seller@example.com',
                'phone_number' => '555-0606',
                'asking_price' => 650000,
                'cash_flow' => 280000,
                'gross_revenue' => 950000,
                'ebitda' => '320000',
                'rent' => '6500',
                'year_established' => 2010,
                'business_description' => 'Well-established dental practice with modern equipment and loyal patient base.',
                'real_estate_type' => 'Leased',
                'building_size' => 2800,
                'employees' => 7,
                'status' => 'published',
            ],
            [
                'headline' => 'Gym with Membership Base',
                'industry' => 'Health Care & Fitness',
                'industry_subcategory' => 'Gyms & Fitness Centers',
                'listing_type' => 'Established Business for Sale',
                'location_name' => 'FitLife Gym',
                'address' => '456 Fitness Way',
                'city' => 'Los Angeles',
                'state' => 'CA',
                'zip' => '90001',
                'location_confidentiality' => 'Exact Location',
                'email' => 'seller@example.com',
                'phone_number' => '555-0707',
                'asking_price' => 380000,
                'cash_flow' => 165000,
                'gross_revenue' => 520000,
                'ebitda' => '185000',
                'rent' => '7500',
                'year_established' => 2015,
                'business_description' => 'Full-service gym with 800+ members and personal training services.',
                'real_estate_type' => 'Leased',
                'building_size' => 10000,
                'employees' => 10,
                'status' => 'draft',
            ]
        ];

        foreach ($listings as $listing) {
            Listing::create(array_merge($listing, [
                'user_id' => 2, // Assign all listings to user with ID 2 (the seller)
                'created_at' => now()->subDays(rand(1, 365)),
                'updated_at' => now()->subDays(rand(0, 30)),
            ]));
        }
    }
}
